[package]
name = "serde-kdl"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
base64 = "0.13.0"
paste = "1.0.5"
serde = "1.0.130"
thiserror = "1.0.29"

[dev-dependencies]
insta = "1.8.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_bytes = "0.11.5"
